# Generated by Django 3.2.9 on 2021-11-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManageMenyu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='F.I.SH')),
                ('title', models.CharField(max_length=250, verbose_name='Lavozimi')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('acceptance_dates', models.CharField(max_length=250, verbose_name='Qabul kunlari')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Tarjimai hol')),
                ('functions_tasks', models.TextField(blank=True, null=True, verbose_name='Funksiya va vazifalar')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Managment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name="Bo'limlar")),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
