# Generated by Django 3.2.9 on 2021-11-10 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('message', models.CharField(max_length=100, verbose_name='Message')),
                ('message_long', models.TextField(verbose_name='Message long')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
        migrations.CreateModel(
            name='Managment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='F.I.SH')),
                ('title', models.CharField(max_length=250, verbose_name='Lavozimi')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('acceptance_dates', models.CharField(max_length=250, verbose_name='Qabul kunlari')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Tarjimai hol')),
                ('functions_tasks', models.TextField(blank=True, null=True, verbose_name='Funksiya va vazifalar')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Rahbaryat',
                'verbose_name_plural': 'Rahbaryat azolari',
            },
        ),
        migrations.CreateModel(
            name='RegionalCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Hududiy boshqarma nomi')),
                ('leader', models.CharField(max_length=250, verbose_name="F.I.SH BOshqarma boshlig'i")),
                ('title', models.CharField(max_length=250, verbose_name='Manzili')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Hududiy bo'lim",
                'verbose_name_plural': "Hududiy bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='F.I.SH')),
                ('title', models.CharField(max_length=250, verbose_name='Lavozimi')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('acceptance_dates', models.CharField(max_length=250, verbose_name='Qabul kunlari')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Tarjimai hol')),
                ('functions_tasks', models.TextField(blank=True, null=True, verbose_name='Funksiya va vazifalar')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Qisqa matn')),
                ('Text', models.TextField(blank=True, null=True, verbose_name='Matin')),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
