# Generated by Django 3.2.9 on 2021-11-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManageMenyu',
        ),
        migrations.RenameField(
            model_name='managment',
            old_name='data',
            new_name='date_time',
        ),
        migrations.AddField(
            model_name='managment',
            name='acceptance_dates',
            field=models.CharField(default=1, max_length=250, verbose_name='Qabul kunlari'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managment',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai hol'),
        ),
        migrations.AddField(
            model_name='managment',
            name='functions_tasks',
            field=models.TextField(blank=True, null=True, verbose_name='Funksiya va vazifalar'),
        ),
        migrations.AddField(
            model_name='managment',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managment',
            name='phone',
            field=models.CharField(default=1, max_length=15, verbose_name='Phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managment',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='Lavozimi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managment',
            name='name',
            field=models.CharField(max_length=250, verbose_name='F.I.SH'),
        ),
    ]
