# Generated by Django 3.2.9 on 2021-11-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20211108_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='F.I.SH')),
                ('title', models.CharField(max_length=250, verbose_name='Lavozimi')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('acceptance_dates', models.CharField(max_length=250, verbose_name='Qabul kunlari')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Tarjimai hol')),
                ('functions_tasks', models.TextField(blank=True, null=True, verbose_name='Funksiya va vazifalar')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.AlterModelOptions(
            name='managment',
            options={'verbose_name': 'Rahbaryat', 'verbose_name_plural': 'Rahbaryat azolar'},
        ),
    ]
