# Generated by Django 3.2.9 on 2021-11-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20211110_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livemessage',
            old_name='message_oz',
            new_name='message_ko',
        ),
        migrations.RenameField(
            model_name='livemessage',
            old_name='message_long_oz',
            new_name='message_long_ko',
        ),
        migrations.RenameField(
            model_name='livemessage',
            old_name='name_oz',
            new_name='name_ko',
        ),
        migrations.RenameField(
            model_name='managment',
            old_name='biography_oz',
            new_name='biography_ko',
        ),
        migrations.RenameField(
            model_name='managment',
            old_name='functions_tasks_oz',
            new_name='functions_tasks_ko',
        ),
        migrations.RenameField(
            model_name='managment',
            old_name='name_oz',
            new_name='name_ko',
        ),
        migrations.RenameField(
            model_name='managment',
            old_name='title_oz',
            new_name='title_ko',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Text_oz',
            new_name='Text_ko',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_oz',
            new_name='title_ko',
        ),
        migrations.RenameField(
            model_name='regionalcenters',
            old_name='leader_oz',
            new_name='leader_ko',
        ),
        migrations.RenameField(
            model_name='regionalcenters',
            old_name='name_oz',
            new_name='name_ko',
        ),
        migrations.RenameField(
            model_name='regionalcenters',
            old_name='title_oz',
            new_name='title_ko',
        ),
        migrations.RenameField(
            model_name='sections',
            old_name='biography_oz',
            new_name='biography_ko',
        ),
        migrations.RenameField(
            model_name='sections',
            old_name='functions_tasks_oz',
            new_name='functions_tasks_ko',
        ),
        migrations.RenameField(
            model_name='sections',
            old_name='name_oz',
            new_name='name_ko',
        ),
        migrations.RenameField(
            model_name='sections',
            old_name='title_oz',
            new_name='title_ko',
        ),
    ]
