# Generated by Django 3.2.9 on 2021-11-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20211108_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managment',
            options={'verbose_name': 'Rahbaryat', 'verbose_name_plural': 'Rahbaryat azolari'},
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Qisqa matn'),
        ),
    ]
