# Generated by Django 3.2.9 on 2021-11-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20211108_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Qisqa matn'),
        ),
    ]
