# Generated by Django 3.2.9 on 2021-11-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20211130_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livemessage',
            old_name='message_long_oz',
            new_name='message_long_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='livemessage',
            old_name='message_oz',
            new_name='message_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='livemessage',
            old_name='name_oz',
            new_name='name_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='managment',
            old_name='biography_oz',
            new_name='biography_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='managment',
            old_name='functions_tasks_oz',
            new_name='functions_tasks_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='managment',
            old_name='name_oz',
            new_name='name_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='managment',
            old_name='title_oz',
            new_name='title_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Text_oz',
            new_name='Text_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_oz',
            new_name='title_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='poster',
            old_name='Text_oz',
            new_name='Text_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='poster',
            old_name='title_oz',
            new_name='title_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='regionalcenters',
            old_name='leader_oz',
            new_name='leader_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='regionalcenters',
            old_name='name_oz',
            new_name='name_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='regionalcenters',
            old_name='title_oz',
            new_name='title_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='sections',
            old_name='biography_oz',
            new_name='biography_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='sections',
            old_name='functions_tasks_oz',
            new_name='functions_tasks_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='sections',
            old_name='name_oz',
            new_name='name_uz_Cyrl',
        ),
        migrations.RenameField(
            model_name='sections',
            old_name='title_oz',
            new_name='title_uz_Cyrl',
        ),
    ]
