# Generated by Django 3.2.9 on 2021-11-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_livemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livemessage',
            name='full_name',
        ),
    ]
